export const languages = {
  ES: {
    games: "Top 20 Juegos",
    games2: "TOP 20 VIDEOJUEGOS",
    created: "© Creado por Rubén Pérez Lara",
    donations: "Donaciones",
    music: "Música",
    list: "LISTAS DE MÚSICA",
    portfolio: "Portafolio",
    duck: "Videojuego",
    prox: "Próximamente",
    shortcut: "Accesos Directos",
    video: "Vídeo",
    link: "LINK AL JUEGO",
    projects: "PROYECTOS",
    dreams1: `Dreams PS4 es un videojuego de PlayStation 4 en el que tu creatividad
    es tu límite. Puedes crear videojuegos, cortos cinematográficos,
    modelaje 3D, música, etc.`,
    dreams2: `Videojuego Rayman 1 recreado en Dreams. Rayman 1 fue lanzado en PlayStation 1, Atari Jaguar y PC. Selector de niveles, nivel 1 y nivel 2 con jefe son jugables. Creado por un fan.`,
    dreams3: `“Videojuego” inspirado en varios juegos actuales. Solo está la beta jugable que contiene cinemática principal y test del juego con sus mecánicas. El proyecto fue creado para aprender los detalles básicos a la hora de crear videojuegos.`,
  },
  EN: {
    games: "Top 20 Games",
    games2: "TOP 20 VIDEOGAMES",
    created: "© Created by Rubén Pérez Lara",
    donations: "Donations",
    music: "Music",
    list: "MUSIC LISTS",
    portfolio: "Portfolio",
    duck: "Videojuego",
    prox: "Coming soon",
    shortcut: "Shortcuts",
    video: "Video",
    link: "LINK TO THE GAME",
    projects: "PROJECTS",
    dreams1: ` Dreams PS4 is a PlayStation 4 video game in which your creativity
    it's your limit. You can create video games, short films,
    3D modeling, music, etc.`,
    dreams2: `Video game Rayman 1 recreated in Dreams. Rayman 1 was released on the PlayStation 1, Atari Jaguar, and PC. Level selector, level 1 and level 2 with boss are playable. Created by a fan.`,
    dreams3: `"Video game" inspired by various current games. There is only the playable beta that contains the main cinematic and game test with its mechanics. The project was created to learn the basic details of creating video games.`,
  },
};
